// See https://github.com/neo4j/graphql/blob/master/packages/graphql/tests/tck/tck-test-files/cypher-pringles.md
{
    MATCH {
        node @node(label: Product) {
            RETURN {
                name
                sizes @edge(type: HAS_SIZE, direction: OUT) {
                    size @node(label: Size) {
                        RETURN {
                            name
                        }
                    }
                }
                photos @edge(type: HAS_PHOTO, direction: OUT) {
                    photo @node(label: Photo) {
                        RETURN {
                            url
                            description
                            color @edge(type: OF_COLOR, direction: OUT) {
                                color @node(label: Color) {
                                    RETURN {
                                        name
                                    }
                                }
                            }
                        }
                    }
                }
            }
        }
    }
}
