FROM node:14.16

WORKDIR /app/src

COPY package.json .
COPY package-lock.json .
COPY jest-global.config.js .
COPY jest-global.setup.js .
COPY lerna.json .
COPY examples ./examples
COPY packages/builder ./packages/builder
COPY packages/client ./packages/client
COPY packages/language ./packages/language

RUN npm ci

CMD ["npm", "test"]