version: 2.1
orbs:
  node: circleci/node@1.1.6
jobs:
  test_suite:
    docker:
      - image: circleci/node:12.16.1
    working_directory: ~/repo
    steps:
      - setup_remote_docker
      - checkout
      - run:
          name: Run Docker Compose Tests
          command: npm run test docker

workflows:
  version: 2
  master_default:
    jobs:
      - test_suite:
          filters:
            branches:
              only: /master/
