version: 2.1
orbs:
  node: circleci/node@4.3.0
jobs:
  test_suite:
    docker:
      - image: circleci/node:14.16
    working_directory: ~/repo
    steps:
      - setup_remote_docker
      - checkout
      - run:
          name: Run Docker Compose Tests
          command: npm run test-docker
  publish:
    docker:
      - image: circleci/node:14.16
    working_directory: ~/repo
    steps:
      - setup_remote_docker
      - checkout
      - run:
          name: Release to npm
          command: NPM_KEY=$NPM_KEY VERSION=$CIRCLE_TAG npm run release
      - add_ssh_keys:
          fingerprints:
            - "f6:ff:d2:0d:1c:2d:12:ff:9c:3d:ea:3f:59:b4:e6:fa"
      - run:
          name: Git User
          command: git config --global user.name "DGQL Publisher"
      - run:
          name: Git Email
          command: git config --global user.email "danielstarns@hotmail.com"
      - run:
          name: Git Add
          command: git add .
      - run:
          name: Git Commit
          command: git commit -m "publish"
      - run:
          name: Git Push
          command: git push origin HEAD:main
workflows:
  version: 2
  main_default:
    jobs:
      - publish:
          requires:
            - test_suite
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^release-.*/
      - test_suite
