version: 2.1
orbs:
  node: circleci/node@4.3.0
jobs:
  test_suite:
    docker:
      - image: circleci/node:14.16
    working_directory: ~/repo
    steps:
      - setup_remote_docker
      - checkout
      - run:
          name: Run Docker Compose Tests
          command: npm run test-docker

workflows:
  version: 2
  main_default:
    jobs:
      - test_suite:
          filters:
            branches:
              only: /main/
