{
  CREATE {
    blog @node(label: Blog) {
      SET {
        id @uuid
        name(value: "Dan's Cool Blog")
        createdAt @datetime
      }
      CREATE @edge(type: AUTHORED, direction: IN) {
        NODE(label: User) {
          SET {
            id @uuid
            name(value: "Dan")
          }
        }
      }
      CREATE @edge(type: HAS_POST, direction: OUT) {
        NODE(label: Post) {
          SET {
            id @uuid
            title(value: "DGQL is cool! Maybe too cool for school!")
            createdAt @datetime
          }
          CONNECT @edge(type: AUTHORED, direction: IN) {
            NODE(label: User) {
              WHERE {
                name(equal: "Dan")
              }
            }
          }
          CREATE @edge(type: HAS_COMMENT, direction: OUT) {
            NODE(label: Comment) {
              SET {
                id @uuid
                content(value: "This is my first comment!")
                createdAt @datetime
              }
              CONNECT @edge(type: AUTHORED, direction: IN) {
                NODE(label: User) {
                  WHERE {
                    name(equal: "Dan")
                  }
                }
              }
            }
          }
        }
      }
      PROJECT {
        name
      }
    }
  }
  RETURN {
    blog
  }
}
