{
    MATCH {
        comments @node(label: Comment) {
            WHERE {
                EDGE(type: COMMENTED, direction: IN) {
                    NODE(label: User) {
                        email(equal: "admin@admin.com")
                    }
                }
            }
        }
    }
    RETURN {
        comments
    }
}
