# See https://neo4j.com/developer/cypher/guide-build-a-recommendation-engine/
{
    MATCH {
        movies @node(label: Movie) {
            WHERE {
                title(equal: "Matrix, The")
            }
            PROJECT {
                title
                imdbRating
                genres
                    @edge(type: IN_GENRE, direction: OUT)
                    @node(label: Genre) {
                    name
                }
                ratings @edge(type: RATED, direction: IN) {
                    to @node(label: User)
                    rating @relationship {
                        PROJECT {
                            rating
                        }
                    }
                }
            }
        }
    }
    RETURN {
        movies
    }
}
